version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: bala
      POSTGRES_PASSWORD: bala
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: bala@gmail.com
      PGADMIN_DEFAULT_PASSWORD: bala
    ports:
      - "5050:80"
    networks:
      - postgres-network
    depends_on:
      - postgres
    volumes:
      - ./pgadmindata:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
